services:
    xgc.influx:
        class: Xgc\InfluxBundle\Service\Influx
        arguments:
            - '@service_container'
    Xgc\InfluxBundle\Service\Influx:
        alias: xgc.influx

    xgc.influx.logger:
        class: Xgc\InfluxBundle\Service\Logger
        arguments:
            - '@service_container'
