# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']
    test:
        class: WebBundle\Service\Test
        arguments: ['@doctrine']

    AdminBundle\Controller\:
        resource: '../../src/AdminBundle/Controller/*'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        public: true
        tags: ['controller.service_arguments']
