AppBundle\Entity\Post:
    type: entity

    fields:
        title:
            type: string
            length: 140
        slug:
            type: string
            length: 140
            unique: true
        text:
            type: text
    manyToOne:
        author:
            targetEntity: AppBundle\Entity\User


